defaults:
  - device: local
  - _self_

exp_name: nerf_experiment

mode: train
is_continue: false

dataset_class_name: WildDataset
dataset:
  image_resize: [2048, 1024]
  image_path: ./example_data/cozy_room/image.png

pose_sampler_name: CirclePoseSampler
pose_sampler:
  traverse_ratios: [0.2, 0.4, 0.6]
  n_anchors_per_ratio: [8, 8, 8]

rgbd_inpaint: false
pers_inpainter_type: stable_diffusion

scene_class_name: NeRFScene
scene:
  estimator_type: occ
  renderer_conf:
    max_radius: 2
    bg_color: rand_noise
  train_conf:
    ignore_near: true
    cross_depth_check: true
    raw_phase_iter_geo: 3000
    raw_phase_iter_app: 1500

    # last_sup_iter: 1000
    # inc_phase_iter: 5000

    geo_optimizer:
      init_lr: 0.0
      peak_lr: 1e-2
      peak_at: 0.2
      lr_alpha: 1e-2

    app_optimizer:
      init_lr: 0.0
      peak_lr: 1e-2
      peak_at: 0.2
      lr_alpha: 1e-2

    prop_optimizer:
      init_lr: 1e-4
      peak_lr: 1e-3
      peak_at: 0.1
      lr_alpha: 0.1


    # loss weights
    color_loss_weight: 1.
    depth_loss_weight: 1.
    density_loss_weight: 0.
    disp_loss_weight: 0.
    opacity_loss_weight: 0.
    distortion_loss_weight: 0.1
    certainty_loss_weight: 0.

    pixel_loss_batch_size: 8192
    vis_adv_patch_freq: 200
    vis_freq: 5000
    vis_video_freq: 25000
    save_freq: 1000000

    patch_real_filter_angle: 45
    patch_fov: 45
    patch_res: 128
